const ADD_IMAGE = 'ADD_IMAGE';
const DELETE_IMAGE = 'DELETE_IMAGE';
const ADD_IMAGES = 'ADD_IMAGES';
const UPDATE_IMAGE = 'UPDATE_IMAGE';

export { ADD_IMAGE, DELETE_IMAGE, ADD_IMAGES, UPDATE_IMAGE };
